version: "3.9"
services:
  db:
    image: mysql:latest
    ports:
      - "3600:3600"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
      - mysql:/var/lib/pease-sql-c

  web:
    build: .
    ports:
      - "5000:5000"




# Names our volume
volumes:
  mysql: